# Build with old debian because buildroot won't on newer
FROM debian:jessie as builder1

RUN sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list && \
    apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y \
        wget \
        curl \
        command-not-found \
        nano \
        vim \
        gcc \
        g++ \
        make \
        git \
        cpio \
        python \
        unzip \
        rsync \
        bc \
        subversion \
        locales \
        build-essential && \
    apt-get clean && \
    sed -i 's/^# *\(en_US.UTF-8\)/\1/' "/etc/locale.gen" && \
    locale-gen

ADD buildroot-2015.11.1.tar.gz /

COPY [".config", "/buildroot-2015.11.1/"]
COPY ["icu4c-56_1-src.tgz", "ipkg-0.99.163.tar.gz", "/buildroot-2015.11.1/dl/"]

RUN make -C "/buildroot-2015.11.1/" && chmod -R a=u "/buildroot-2015.11.1"
